# PMAT Configuration for Reaper Project
# Extreme quality standards for Ruchy showcase

[project]
name = "reaper"
version = "0.1.0"
language = "ruchy"

[quality]
# Technical Debt Grading thresholds
min_grade = "A"  # A or A+ required
max_complexity = 10
max_cognitive_complexity = 7
min_score = 93.0  # A grade threshold

# SATD (Self-Admitted Technical Debt) tolerance
satd_tolerance = 0  # Zero TODO/FIXME/HACK allowed

[coverage]
min_coverage = 0.80  # 80% minimum
target_coverage = 0.90  # 90% target

[mutation]
min_mutation_score = 0.80  # 80% minimum
target_mutation_score = 0.90  # 90% target

[analysis]
# Paths to analyze
include = ["src/**/*.ruchy", "tests/**/*.ruchy"]
exclude = ["target/**", ".git/**"]

# Language-specific settings
[analysis.ruchy]
enabled = true
strict_mode = true

[hooks]
# Git hooks configuration
pre_commit = true
post_commit = false
pre_push = true

[mcp]
# MCP server configuration (for Claude Code integration)
enabled = true
port = 9090
tools = ["tdg", "complexity", "satd", "coverage"]
